"""One-way sequence import, generated views, and selection eligibility.

Three responsibilities, in one direction each. `import_sequence` reads a
pre-import `SEQUENCE.md`: it plans by default and writes nothing, and applies
only on explicit confirmation, through `store.apply_import` so the transformation
lands as one journalled operation ending in one commit. It then re-derives the
sequence from the stored records and compares it with the source entry by entry,
because success is never declared from an exit code. `render` writes the
generated sequence and task views, which are replaceable output and never an
authority. `select` returns one candidate and the reasons every considered item
was or was not eligible; it starts nothing.

Parent task counts and indexes are derived here on every read, never stored in a
record.
"""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path

from session_flow import InvalidIdentityError, InvalidRequestError
from session_flow import store
from session_flow.records import (
    DEFAULT_ORDER,
    DEFAULT_PRIORITY,
    INTENT_FILE,
    LIFECYCLE_CAPTURED,
    LIFECYCLE_STATES,
    PRIORITY_RANK,
    RECORD_FORMAT_VERSION,
    TASKS_DIRECTORY,
    acceptance_status,
    check_namespace,
    ensure_within,
    escape_markers,
    item_directory,
    lifecycle_of,
    parse_item_id,
    parse_namespace,
    read_record,
    render_record,
    unescape_markers,
    validate_lifecycle,
)

ENTRY_RE = re.compile(
    r"^- \[(?P<marker> |x|X|DEFERRED)\] (?P<seq>SEQ-[0-9]{3,6})"
    r" (?P<priority>P[0-9]+)(?P<auto> \[auto\])?: (?P<rest>.+)$"
)
ANNOTATION_RE = re.compile(r" ⇄ (?P<url>\S+)$")
LOOKS_LIKE_ENTRY_RE = re.compile(r"^\s*[-*] \[")
COMMENT_RE = re.compile(r"^\s*<!--.*-->\s*$")
NEEDS_BREAKDOWN = " (needs breakdown)"
LINK_TOKEN = " → "
ANNOTATION_TOKEN = " ⇄ "

MARKER_STATES = {" ": "captured", "x": "done", "X": "done", "DEFERRED": "deferred"}
STATE_MARKERS = dict.fromkeys(LIFECYCLE_STATES, "[ ]")
STATE_MARKERS.update({"done": "[x]", "deferred": "[DEFERRED]", "cancelled": "[DEFERRED]"})
ELIGIBLE_STATES = ("accepted", "active")
ITEM_DIRECTORY_RE = re.compile(r"^seq-[0-9]{3,6}$")
TASK_VIEW_FILE = "_index.md"
IDENTITY_RE = re.compile(r"\bSEQ-[0-9]{3,6}\b")
HISTORICAL_PATH_KEYS = ("todo", "tasks")
TOMBSTONE_IMPORTED = "imported"
TOMBSTONE_HISTORICAL = "historical"
COMPARED_FIELDS = (
    "seq",
    "lifecycle",
    "priority",
    "auto",
    "title",
    "annotations",
    "links",
    "needs_breakdown",
    "notes",
)

SEQUENCE_HEADER = (
    "# Task Sequence\n\n"
    "Generated by session-flow from the work root. Do not edit this file: change the work item "
    "and re-run `session-flow.py render`.\n"
)
TASK_VIEW_HEADER = "Generated by session-flow. Do not edit this file: it is derived from the task records.\n"
IMPORT_BODY = (
    "## Original entry\n\n"
    "Imported verbatim from the pre-import sequence. No intent, acceptance, or completion was "
    "inferred from it.\n\n"
    "    {entry}\n"
)


def split_trailing_token(rest: str) -> tuple[str, dict]:
    """Strip the one trailing status token from an entry's text after the priority."""
    if rest.endswith(NEEDS_BREAKDOWN):
        return rest[: -len(NEEDS_BREAKDOWN)], {"needs_breakdown": True}
    head, token, link = rest.rpartition(LINK_TOKEN)
    if not token:
        return rest, {}
    target, _, anchor = link.partition("#")
    links = {"breakdown": target}
    if anchor:
        links["anchor"] = anchor
    return head, {"links": links}


def split_annotations(text: str) -> tuple[str, list[str]]:
    annotations = []
    while True:
        match = ANNOTATION_RE.search(text)
        if match is None:
            return text, list(reversed(annotations))
        annotations.append(match.group("url"))
        text = text[: match.start()]


def parse_entry(line: str) -> dict | None:
    """Parse one sequence entry line into an item, or return None when it is not one."""
    match = ENTRY_RE.match(line)
    if match is None:
        return None
    rest, trailing = split_trailing_token(match.group("rest"))
    title, annotations = split_annotations(rest)
    entry = {
        "seq": parse_item_id(match.group("seq")),
        "lifecycle": MARKER_STATES[match.group("marker")],
        "priority": match.group("priority"),
        "auto": match.group("auto") is not None,
        "title": title,
        "annotations": annotations,
        "notes": [],
    }
    entry.update(trailing)
    return entry


def parse_sequence(text: str) -> dict:
    """Parse every entry line, keeping the HTML comment lines that follow each entry."""
    entries: list[dict] = []
    unclassified: list[dict] = []
    for number, line in enumerate(text.splitlines(), start=1):
        entry = parse_entry(line.rstrip())
        if entry is not None:
            entry["order"] = len(entries) + 1
            entries.append(entry)
            continue
        if entries and COMMENT_RE.match(line):
            entries[-1]["notes"].append(line.strip())
            continue
        if LOOKS_LIKE_ENTRY_RE.match(line):
            unclassified.append({"line": number, "text": line.rstrip()})
    return {"entries": entries, "unclassified": unclassified}


def reject_duplicate_ids(entries: list[dict]) -> None:
    seen: dict[str, int] = {}
    for entry in entries:
        first = seen.get(entry["seq"])
        if first is not None:
            raise InvalidIdentityError(
                f"{entry['seq']} appears on lines {first} and {entry['order']} of the sequence; two "
                "rows cannot claim one identity, so resolve the duplicate before importing",
                seq=entry["seq"],
            )
        seen[entry["seq"]] = entry["order"]


def import_source(request: dict) -> Path:
    payload = request.get("input") or {}
    supplied = payload.get("source")
    if supplied is None:
        return Path(request["sequence_path"])
    return ensure_within(request["project_root"], Path(request["project_root"]) / supplied)


def read_source(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise InvalidIdentityError(
            f"cannot read the sequence at {path} ({error.strerror}); pass "
            '{"source": "<path>"} in --input to name the pre-import file',
            path=str(path),
        ) from error


def require_namespace(request: dict) -> str:
    namespace = request.get("namespace")
    if namespace is None:
        raise InvalidIdentityError(
            "import needs --namespace <uuid>; copy the `namespace` value from the work root's "
            "namespace.json so imported records carry their owning namespace"
        )
    return parse_namespace(namespace)


def read_markdown(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise InvalidIdentityError(
            f"cannot read the pre-import file {path} ({error.strerror}); every historical file must "
            "be readable before its identities are retired, so fix its permissions and re-run",
            path=str(path),
        ) from error


def historical_roots(request: dict) -> list[Path]:
    """The pre-import directories scanned for identities no live entry carries."""
    project_root = Path(request["project_root"])
    named = (request.get("input") or {}).get("historical")
    if named is None:
        configured = request.get("config") or {}
        paths = configured.get("paths") if isinstance(configured.get("paths"), dict) else {}
        candidates = [
            project_root / paths[key] for key in HISTORICAL_PATH_KEYS if isinstance(paths.get(key), str)
        ]
    elif isinstance(named, list) and all(isinstance(entry, str) for entry in named):
        candidates = [ensure_within(project_root, project_root / entry) for entry in named]
    else:
        raise InvalidRequestError(
            "`historical` must be a list of project-relative directories to scan for retired "
            "identities; omit it to scan the configured todo and tasks paths"
        )
    return [path for path in candidates if path.is_dir()]


def historical_ids(request: dict, known: set) -> list[str]:
    """Identities surviving only in a pre-import file. They are retired, never reallocated."""
    work_root = Path(request["work_root"])
    found: set = set()
    for root in historical_roots(request):
        for path in sorted(root.rglob("*.md")):
            if work_root == path or work_root in path.parents:
                continue
            found.update(IDENTITY_RE.findall(read_markdown(path)))
    return sorted(found - known)


def tombstone_entries(request: dict, items: list[dict]) -> list[dict]:
    """Every identity the survey saw, each with the reason it can never be allocated again."""
    imported = sorted(item["metadata"]["seq"] for item in items)
    return [{"seq": seq, "state": TOMBSTONE_IMPORTED} for seq in imported] + [
        {"seq": seq, "state": TOMBSTONE_HISTORICAL}
        for seq in historical_ids(request, set(imported))
    ]


def unresolved_links(entries: list[dict], project_root) -> list[dict]:
    """Entries whose breakdown link names a file that is not where the entry says it lies."""
    dangling = []
    for entry in entries:
        target = (entry.get("links") or {}).get("breakdown")
        if target is None or (Path(project_root) / target).is_file():
            continue
        dangling.append({"seq": entry["seq"], "link": target})
    return dangling


def plan_import(request: dict) -> dict:
    """Transform a pre-import sequence into work items. Writes nothing."""
    namespace = require_namespace(request)
    source = import_source(request)
    parsed = parse_sequence(read_source(source))
    reject_duplicate_ids(parsed["entries"])
    root = request["project_root"]
    items = [imported_item(entry, namespace, source, root) for entry in parsed["entries"]]
    return {
        "source": str(source),
        "items": items,
        "tombstones": tombstone_entries(request, items),
        "unclassified": parsed["unclassified"],
        "unresolved_links": unresolved_links(parsed["entries"], root),
    }


def refuse_unclassified(plan: dict) -> None:
    unclassified = plan["unclassified"]
    if not unclassified:
        return
    first = unclassified[0]
    raise InvalidIdentityError(
        f"the survey cannot classify {len(unclassified)} line(s) of {plan['source']}, the first at "
        f"line {first['line']}: {first['text']!r}; importing would drop them, so rewrite them to "
        "the grammar in references/sequence-grammar.md and re-run",
        source=plan["source"],
        unclassified=unclassified,
    )


def refuse_dangling_links(plan: dict) -> None:
    dangling = plan["unresolved_links"]
    if not dangling:
        return
    first = dangling[0]
    raise InvalidIdentityError(
        f"{len(dangling)} entry link(s) name a file that is not there, the first {first['seq']} "
        f"→ {first['link']}; import links historical files where they lie, so restore or correct "
        "each target and re-run",
        unresolved_links=dangling,
    )


def derived_entries(request: dict) -> list[dict]:
    """Re-derive the sequence from the stored records, through the generated view."""
    return parse_sequence(render_sequence(load_items(request)))["entries"]


def first_difference(original: dict, derived: dict) -> str | None:
    for field in COMPARED_FIELDS:
        if original.get(field) != derived.get(field):
            return field
    return None


def round_trip_failure(original: list[dict], derived: list[dict]) -> dict | None:
    """The first way the re-derived sequence differs from the original, or None."""
    wanted = [entry["seq"] for entry in original]
    kept = [entry for entry in derived if entry["seq"] in set(wanted)]
    if [entry["seq"] for entry in kept] != wanted:
        return {
            "reason": "the stored records do not re-derive the same identities in the same order",
            "expected": wanted,
            "found": [entry["seq"] for entry in kept],
        }
    for source_entry, derived_entry in zip(original, kept):
        field = first_difference(source_entry, derived_entry)
        if field is not None:
            return {
                "reason": f"{source_entry['seq']} did not survive the import with its {field} intact",
                "seq": source_entry["seq"],
                "field": field,
                "expected": source_entry.get(field),
                "found": derived_entry.get(field),
            }
    return None


def link_failure(entries: list[dict], project_root) -> dict | None:
    dangling = unresolved_links(entries, project_root)
    if not dangling:
        return None
    return {
        "reason": f"{len(dangling)} imported link(s) resolve to no file",
        "unresolved_links": dangling,
    }


def commit_reference(commit) -> str:
    """The commit to revert, or why this run left none."""
    if not isinstance(commit, dict):
        return "no commit, because this run wrote nothing"
    if commit.get("commit"):
        return str(commit["commit"])
    return "no commit: " + str(commit.get("reason", "the work root was not committed"))


def verify_round_trip(request: dict, source: str, commit) -> dict:
    """Compare the re-derived sequence with the source entry by entry, or fail the run."""
    original = parse_sequence(read_source(Path(source)))["entries"]
    derived = derived_entries(request)
    failure = round_trip_failure(original, derived) or link_failure(
        derived, request["project_root"]
    )
    if failure is None:
        return {"verified": True, "entries": len(original), "source": str(source)}
    raise InvalidIdentityError(
        f"the round-trip comparison failed: {failure['reason']}; the import is already committed "
        f"as {commit_reference(commit)}, so revert that commit instead of reading the exit code "
        "as success",
        commit=commit_reference(commit),
        mismatch=failure,
    )


def import_sequence(request: dict) -> dict:
    """Plan the import by default; apply and verify it only on explicit confirmation."""
    plan = plan_import(request)
    if not (request.get("input") or {}).get("apply"):
        return dict(plan, applied=False)
    refuse_unclassified(plan)
    refuse_dangling_links(plan)
    operation = store.apply_import(request, request["input"], plan)
    return {
        "source": plan["source"],
        "applied": True,
        "imported": [item["metadata"]["seq"] for item in plan["items"]],
        "tombstones": plan["tombstones"],
        "unclassified": plan["unclassified"],
        "operation": operation,
        "verification": verify_round_trip(request, plan["source"], operation.get("commit")),
    }


def imported_item(entry: dict, namespace: str, source: Path, project_root: str) -> dict:
    """Build one item: its record path, its metadata, and the record text to write.

    Captured title and comment text is stored with its structural markers escaped,
    so no imported line can open or close a record region.
    """
    try:
        origin = str(Path(source).relative_to(project_root))
    except ValueError:
        origin = str(source)
    metadata = {
        "format": RECORD_FORMAT_VERSION,
        "namespace": namespace,
        "seq": entry["seq"],
        "revision": 1,
        "title": escape_markers(entry["title"]),
        "lifecycle": entry["lifecycle"],
        "priority": entry["priority"],
        "order": entry["order"],
        "provenance": {"auto": entry["auto"], "imported_from": origin},
    }
    for field in ("annotations", "links", "needs_breakdown"):
        if entry.get(field):
            metadata[field] = entry[field]
    if entry["notes"]:
        metadata["notes"] = [escape_markers(note) for note in entry["notes"]]
    body = IMPORT_BODY.format(entry=render_entry(view_fields(metadata, entry["seq"])))
    return {
        "path": f"{item_directory(entry['seq'])}/{INTENT_FILE}",
        "metadata": metadata,
        "text": render_record(metadata, entry["title"], body),
    }


def view_fields(metadata: dict, seq: str) -> dict:
    """The view-bearing fields of one record. Priority and order default as `records` does."""
    provenance = metadata.get("provenance") if isinstance(metadata.get("provenance"), dict) else {}
    order = metadata.get("order")
    return {
        "seq": seq,
        "title": unescape_markers(metadata.get("title", "")),
        "lifecycle": validate_lifecycle(metadata.get("lifecycle", LIFECYCLE_CAPTURED)),
        "priority": metadata.get("priority") or DEFAULT_PRIORITY,
        "order": order if type(order) is int else DEFAULT_ORDER,
        "auto": bool(provenance.get("auto")),
        "annotations": list(metadata.get("annotations", [])),
        "links": dict(metadata.get("links", {})),
        "needs_breakdown": bool(metadata.get("needs_breakdown")),
        "notes": [unescape_markers(note) for note in metadata.get("notes", [])],
    }


def render_entry(item: dict) -> str:
    """Render one entry line: marker, identity, priority, provenance, annotations, one token."""
    auto = " [auto]" if item["auto"] else ""
    annotations = "".join(ANNOTATION_TOKEN + url for url in item["annotations"])
    trailing = ""
    if item["links"].get("breakdown"):
        anchor = item["links"].get("anchor")
        trailing = LINK_TOKEN + item["links"]["breakdown"] + ("#" + anchor if anchor else "")
    elif item["needs_breakdown"]:
        trailing = NEEDS_BREAKDOWN
    marker = STATE_MARKERS[item["lifecycle"]]
    return (
        f"- {marker} {item['seq']} {item['priority']}{auto}: "
        f"{item['title']}{annotations}{trailing}"
    )


def render_sequence(items: list[dict]) -> str:
    lines = [SEQUENCE_HEADER]
    for entry in sorted(items, key=lambda item: (item["order"], item["seq"])):
        lines.append("\n".join([render_entry(entry)] + entry["notes"]))
    return "\n".join(lines) + "\n"


def task_records(directory: Path) -> list[dict]:
    tasks_directory = directory / TASKS_DIRECTORY
    if not tasks_directory.is_dir():
        return []
    files = sorted(path for path in tasks_directory.glob("*.md") if not path.name.startswith("_"))
    tasks = []
    for index, path in enumerate(files, start=1):
        record = read_record(path)
        tasks.append(
            {
                "task": record["identity"].get("task", path.stem),
                "index": index,
                "lifecycle": lifecycle_of(record),
                "path": str(path),
            }
        )
    return tasks


def load_items(request: dict) -> list[dict]:
    """Read every work item from the work root, deriving task indexes and counts."""
    work_root = Path(request["work_root"])
    if not work_root.is_dir():
        raise InvalidIdentityError(
            f"no work root at {work_root}; run session-init or point paths.work at the work root",
            work_root=str(work_root),
        )
    items = []
    for directory in sorted(work_root.iterdir()):
        if not directory.is_dir() or not ITEM_DIRECTORY_RE.match(directory.name):
            continue
        record = read_record(directory / INTENT_FILE)
        check_namespace(record["identity"], request.get("namespace"))
        item = view_fields(record["metadata"], record["identity"]["seq"])
        item["lifecycle"] = lifecycle_of(record)
        item["acceptance"] = acceptance_status(record)
        tasks = task_records(directory)
        item["tasks"] = tasks
        item["task_counts"] = {
            "total": len(tasks),
            "done": sum(1 for task in tasks if task["lifecycle"] == "done"),
        }
        item["path"] = str(directory / INTENT_FILE)
        item["directory"] = str(directory)
        items.append(item)
    return items


def render_task_view(item: dict) -> str:
    counts = item["task_counts"]
    lines = [
        f"# {item['seq']} tasks",
        "",
        TASK_VIEW_HEADER.rstrip("\n"),
        "",
        f"{counts['total']} tasks, {counts['done']} done.",
        "",
        "| Index | Task | Lifecycle |",
        "|---|---|---|",
    ]
    for task in item["tasks"]:
        lines.append(
            f"| {task['index']} | {item['seq']}/{task['task']} | {task['lifecycle']} |"
        )
    return "\n".join(lines) + "\n"


def write_generated(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=str(path.parent), prefix=".session-flow-view-", delete=False
    )
    with handle:
        handle.write(text)
    os.replace(handle.name, str(path))
    return str(path)


def render(request: dict) -> dict:
    """Write the sequence view and one task view per item that has task records."""
    items = load_items(request)
    written = [write_generated(Path(request["sequence_path"]), render_sequence(items))]
    for item in items:
        if not item["tasks"]:
            continue
        path = Path(item["directory"]) / TASKS_DIRECTORY / TASK_VIEW_FILE
        written.append(write_generated(path, render_task_view(item)))
    return {"sequence": str(request["sequence_path"]), "generated": written, "items": len(items)}


def acceptance_reason(status: dict) -> str | None:
    """Why the derived acceptance status blocks this item, or None when it applies."""
    if status["applies"]:
        return None
    if not status["accepted"]:
        return (
            f"no acceptance names the current scope fingerprint {status['fingerprint']}; a breakdown "
            "link alone confers no eligibility"
        )
    return (
        f"acceptance names {status['accepted_fingerprint']} but the scope is now "
        f"{status['fingerprint']}; re-accept the scope or record the edit with a same-meaning decision"
    )


def ineligibility_reasons(item: dict) -> list[str]:
    """Every reason this item cannot be worked. Empty means eligible."""
    reasons = []
    if item["lifecycle"] not in ELIGIBLE_STATES:
        reasons.append(
            f"lifecycle is {item['lifecycle']}; only {' or '.join(ELIGIBLE_STATES)} work is eligible"
        )
    if item["needs_breakdown"]:
        reasons.append("the item is still marked (needs breakdown)")
    acceptance = acceptance_reason(item["acceptance"])
    if acceptance is not None:
        reasons.append(acceptance)
    return reasons


def candidate_order(item: dict) -> tuple:
    """Priority, then provenance, then order, then identity: `[auto]` never outranks a request."""
    rank = PRIORITY_RANK.get(item["priority"], len(PRIORITY_RANK))
    return rank, int(item["auto"]), item["order"], item["seq"]


def considered_entry(item: dict) -> dict:
    reasons = ineligibility_reasons(item)
    return {
        "seq": item["seq"],
        "lifecycle": item["lifecycle"],
        "eligible": not reasons,
        "reasons": reasons,
    }


def candidate_payload(item: dict) -> dict:
    return {
        "seq": item["seq"],
        "title": item["title"],
        "lifecycle": item["lifecycle"],
        "priority": item["priority"],
        "order": item["order"],
        "acceptance": item["acceptance"],
        "path": item["path"],
        "tasks": item["tasks"],
        "task_counts": item["task_counts"],
    }


def select(request: dict) -> dict:
    """Return one candidate and the eligibility reasons for every item considered."""
    items = load_items(request)
    if request.get("seq"):
        wanted = parse_item_id(request["seq"])
        items = [item for item in items if item["seq"] == wanted]
        if not items:
            raise InvalidIdentityError(
                f"no work item {wanted} in {request['work_root']}; capture it before selecting it",
                seq=wanted,
            )
    considered = [considered_entry(item) for item in items]
    open_work = (item for item, entry in zip(items, considered) if entry["eligible"])
    eligible = sorted(open_work, key=candidate_order)
    return {
        "candidate": candidate_payload(eligible[0]) if eligible else None,
        "considered": considered,
        "eligible": len(eligible),
    }
